# Generated by Django 2.0.9 on 2018-12-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilename',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
